first commit
bkostanetskyi/Books pull request #1
Opened 2024-09-16 17:17 UTC by bkostanetskyi

2024-09-17 16:47 UTC, Elena-Bruyako requested changes
see comments

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            Book book1 = new Book();
don't use numbers for naming

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            book1.setTitle("Book 1");
you should create book and call BookService methods

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/model/Book.java
> +@Entity
```suggestion
@Entity
@Table....
@Getter
@Setter
```

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/model/Book.java
> +    // Getter-и та Setter-и
remove getters and setters

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/model/Book.java
> +    @Column
```suggestion
```

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +        books.add(book);
implement adding book to database

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +        return new ArrayList<>(books);
implement find all books from database

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-09-17 16:47 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/service/BookServiceImpl.java
> +    }
```suggestion
```

2024-09-17 19:03 UTC, Elena-Bruyako requested changes
see comments

2024-09-17 19:03 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +        return sessionFactory.getCurrentSession()
add try catch

2024-09-17 19:03 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            bookRepository.save(book);
you should create Book, save it and call findAll books here

2024-09-17 19:03 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +            }
throw new DataProcessingException

2024-09-17 19:03 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-09-18 12:33 UTC, Elena-Bruyako requested changes
see comments
If you have some questions please ask in chat

2024-09-18 12:33 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            bookRepository.save(book);
Comment wasn't fixed.

2024-09-18 12:33 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +            }
comment wasn't fixed

2024-09-18 12:33 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +        try {
use try with resources

2024-09-18 12:33 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +        List<Book> books = new ArrayList<>();
remove

2024-09-18 12:45 UTC, Elena-Bruyako requested changes
see comments

2024-09-18 12:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            bookRepository.save(book);
You should call BookService methods, I mentioned this here https://github.com/bkostanetskyi/Books/pull/1#discussion_r1763563436

Implement this comment and run you application locally to get the result

2024-09-18 12:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +            }
throw new DataProcessingException

2024-09-18 13:05 UTC, Elena-Bruyako requested changes

2024-09-18 13:05 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +    private BookRepository bookRepository;
```suggestion
    private BookService bookService;
```

2024-09-18 13:05 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            bookRepository.save(book);
```suggestion
            bookService.save(book);
```

2024-09-18 13:05 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/BooksApplication.java
> +            List<Book> books = bookRepository.findAll();
```suggestion
            List<Book> books = bookService.findAll();
```

see the result on console

2024-09-18 13:05 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +            throw new DataProcessingException("Error occurred during data processing", e);
```suggestion
            throw new DataProcessingException("Can't save the book", e);
```

2024-09-18 13:05 UTC, Elena-Bruyako commented on src/main/java/mate/academy/books/repository/BookRepositoryImpl.java
> +            return session.createQuery("from Book", Book.class).list();
```suggestion
            return session.createQuery("from Book", Book.class).getResultList();
```

2024-09-18 21:57 UTC, sarakhmen approved these changes
lgtm!

2024-09-19 19:19 UTC, merged